export const FETCH_QUOTE_REQUEST = "FETCH_QUOTE_REQUEST";
export const FETCH_QUOTE_SUCCESS = "FETCH_QUOTE_SUCCESS";
export const FETCH_QUOTE_FAILURE = "FETCH_QUOTE_FAILURE";
export const SET_ANIME_NAME = "SET_ANIME_NAME";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
